name: Create Patch Tag on Release Merge

on:
  push:
    branches:
      - release/**

jobs:
  create_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: composer ci

      - name: Extract release version
        id: extract
        run: |
          git fetch --tags
          base_branch="${GITHUB_REF#refs/heads/release/}"
          echo "RELEASE_BASE=$base_branch" >> $GITHUB_ENV

      - name: Get next patch version
        id: next_patch
        run: |
          major=$(echo "$RELEASE_BASE" | cut -d. -f1)
          minor=$(echo "$RELEASE_BASE" | cut -d. -f2)
          patch=$(echo "$RELEASE_BASE" | cut -d. -f3)
          current_prefix="$major.$minor"
          echo "current: $current_prefix"

          current_patch=$(git tag --sort=-v:refname | grep -E "^$current_prefix\.[0-9]+$" | head -n 1)
          IFS='.' read -r -a VERSION <<< "$current_patch"
          VERSION[2]=$((VERSION[2] + 1))
          new_tag="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"
          echo "Next patch: $new_tag";
          echo "NEW_PATCH=$new_tag" >> $GITHUB_ENV

      - name: Create and push patch tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "${{ env.NEW_PATCH }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Quantum-Tecnology/Actions.git
          git push origin "${{ env.NEW_PATCH }}"